name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        stack-version: 'latest'
        enable-stack: true

    - name: Cache Stack dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Install dependencies
      run: stack build --only-dependencies

    - name: Build project (release mode)
      run: stack build --ghc-options="-O2 -optc-O3"

    - name: Build executable for release
      run: stack install --local-bin-path ./release

    - name: Get project name
      id: project_info
      run: |
        PROJECT_NAME=$(stack query locals | grep -E "^[^[:space:]]*:" | head -n1 | cut -d: -f1)
        echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT
        echo "Project name: $PROJECT_NAME"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.project_info.outputs.project_name }}-release
        path: release/
        retention-days: 30